# Generated by Django 4.2.3 on 2023-09-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='curs/', verbose_name='Превью')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': ('Урок',),
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
